### PR TITLE
 Refactor the repo structure to add sub modules

### PR DESCRIPTION
**Pull request by dubdabasoduba**

### CODE REVIEW

**Review by rehammuzzamil — COMMENTED** [review]
Looks good to me.

**Review by rehammuzzamil — COMMENTED** [review]
Looks good to me.
@dubdabasoduba  do we need to test it out before merging it to main?

**Comment by dubdabasoduba** [comment]
> Looks good to me.
> @dubdabasoduba do we need to test it out before merging it to main?

@rehammuzzamil Yes please

**Comment by rehammuzzamil** [comment]
> > Looks good to me.
> > @dubdabasoduba do we need to test it out before merging it to main?
> 
> @rehammuzzamil Yes please

Sure, will do. Thanks.

**Review by ndegwamartin — APPROVED** [review]

**Pull request merged**
